query Introspection {__schema{queryType{name}mutationType{name}subscriptionType{name}types{...FullType}directives{name description locations args{...InputValue}}}}fragment FullType on __Type{kind name description fields(includeDeprecated:true){name description args{...InputValue}type{...TypeRef}isDeprecated deprecationReason}inputFields{...InputValue}interfaces{...TypeRef}enumValues(includeDeprecated:true){name description isDeprecated deprecationReason}possibleTypes{...TypeRef}}fragment InputValue on __InputValue{name description type{...TypeRef}defaultValue}fragment TypeRef on __Type{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name}}}}}}}}

query Builtins {
  health
  apiVersion
  appVersion
}

mutation SecretC {
  secret: createSecret(secret: {name: "SHODAN", value: "test"}) {
    id
    name
    value
    timestamp: createdAt
  }
}

query SecretR {
  secrets: secrets {
    id
    name
    value
    timestamp: createdAt
  }
}

mutation EventC {
  paste: createEvent(keywordId: 1, event: {template: "playground", type: PASTE, source: "https://kike.wtf/", data: "Cupcake ipsum dolor sit amet croissant bonbon. I love wafer jelly jelly beans I love. Pudding biscuit chocolate cake gingerbread lollipop jelly-o jelly-o. Gummies croissant tiramisu halvah toffee caramels. Cake danish toffee macaroon chocolate dessert chocolate cake cotton candy. Dragée chocolate cake jelly-o cookie apple pie liquorice liquorice. Liquorice chupa chups I love dessert cake I love apple pie ice cream."}) {
    id
    template
    type
    source
    data
    createdAt
    keywords {
      id
      type
      value
      timestamp: createdAt
      lastConsulted
    }
  }
}

query EventR {
  firstEvent: event(id: 1) {
    id
    template
    type
    source
    data
    createdAt
    keywords {
      id
      type
      value
      timestamp: createdAt
      lastConsulted
    }
  }
  
  events: events {
    id
    template
    type
    source
    data
    createdAt
    keywords {
      id
      type
      value
      timestamp: createdAt
      lastConsulted
    }
  }
}

mutation KeywordC {
  domain: createKeyword(keyword: {type: TEXT, value: "func"}) {
    id
    type
    value
    createdAt
    lastConsulted
    events {
      id
      template
      type
      source
      data
      createdAt
    }
  }
}

query KeywordR {
  firstKeyword: keyword(id: 1) {
    id
    type
    value
    createdAt
    lastConsulted
    events {
      id
      template
      type
      source
      data
      createdAt
    }
  }

  keywords: keywords {
    id
    type
    value
    createdAt
    lastConsulted
    events {
      id
      template
      type
      source
      data
      createdAt
    }
  }
}
