---
version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    ports: ["${POSTGRES_PORT:-5432}:5432"]
    volumes:
      - db:/var/lib/postgresql/data:rw
      - ./db/01-up.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      POSTGRES_USER:      ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD:  ${POSTGRES_PASS:-postgres}
      POSTGRES_DB:        ${POSTGRES_NAME:-intelligencce}

volumes:
  db: